BASE: ['']
TOOLBOX_MODE: "only_test"
TRAIN:
  BATCH_SIZE: 1
  EPOCHS: 30
  LR: 1e-4
  MODEL_FILE_NAME: PhysLLM_PhaseNet_JOINT_UBFC_PURE_BUAA_MMPD_72x72_160
  PLOT_LOSSES_AND_LR: false
  DATA:
    INFO:
      LIGHT: [1, 2, 3, 4]
      MOTION: [1, 2, 3, 4]
      EXERCISE: [1, 2]
      SKIN_COLOR: [3, 4, 5, 6]
      GENDER: [1, 2]
      GLASSER: [1, 2]
      HAIR_COVER: [1, 2]
      MAKEUP: [1, 2]
    FS: 30
    DATASET: JOINT
    DO_PREPROCESS: false
    DATA_FORMAT: NCDHW
    DATA_PATH: "/public_hw/share/cit_ztyu/zhaobo/rPPG_dataset_processed/JOINT"
    CACHED_PATH: "/public_hw/share/cit_ztyu/zhaobo/rPPG_dataset_processed/JOINT"
    FILE_LIST_PATH: "/public_hw/share/cit_ztyu/zhaobo/rPPG_dataset_processed/JOINT/DataFileLists/Joint_UBFC_PURE_BUAA_MMPD_72x72_160_Raw_Standardized_train_hrbin250_balanced_polarity.csv"
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 1.0
    PREPROCESS:
      DATA_TYPE: ['Raw']
      DATA_AUG: ['None']
      LABEL_TYPE: Standardized
      DO_CHUNK: True
      CHUNK_LENGTH: 160
      CROP_FACE:
        DO_CROP_FACE: True
        BACKEND: 'HC'
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY: 30
          USE_MEDIAN_FACE_BOX: False
      RESIZE:
        H: 72
        W: 72
VALID:
  DATA:
    FS: 30
    DATASET: None
    DO_PREPROCESS: false
    DATA_FORMAT: NCDHW
    DATA_PATH: ""
    CACHED_PATH: ""
    FILE_LIST_PATH: ""
    EXP_DATA_NAME: ""
    BEGIN: 0.8
    END: 1.0
    PREPROCESS:
      DATA_TYPE: ['Raw']
      DATA_AUG: ['None']
      LABEL_TYPE: Standardized
      DO_CHUNK: True
      CHUNK_LENGTH: 160
      CROP_FACE:
        DO_CROP_FACE: True
        BACKEND: 'HC'
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY: 30
          USE_MEDIAN_FACE_BOX: False
      RESIZE:
        H: 72
        W: 72
TEST:
  METRICS: ['MAE', 'RMSE', 'MAPE', 'Pearson', 'SNR']
  USE_LAST_EPOCH: true
  DATA:
    INFO:
      LIGHT: [1, 2, 3, 4]
      MOTION: [1, 2, 3, 4]
      EXERCISE: [1, 2]
      SKIN_COLOR: [3, 4, 5, 6]
      GENDER: [1, 2]
      GLASSER: [1, 2]
      HAIR_COVER: [1, 2]
      MAKEUP: [1, 2]
    FS: 30
    DATASET: PURE
    DO_PREPROCESS: false
    DATA_FORMAT: NCDHW
    DATA_PATH: "/public_hw/share/cit_ztyu/zhaobo/rPPG_dataset_processed/PURE"
    CACHED_PATH: "/public_hw/share/cit_ztyu/zhaobo/rPPG_dataset_processed/PURE"
    FILE_LIST_PATH: "/public_hw/share/cit_ztyu/zhaobo/rPPG_dataset_processed/PURE/DataFileLists/PURE_SizeW72_SizeH72_ClipLength160_DataTypeRaw_DataAugNone_LabelTypeStandardized_Crop_faceTrue_BackendHC_Large_boxTrue_Large_size1.5_Dyamic_DetFalse_det_len30_Median_face_boxFalse_0.0_1.0.csv"
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 1.0
    PREPROCESS:
      DATA_TYPE: ['Raw']
      LABEL_TYPE: Standardized
      DO_CHUNK: True
      CHUNK_LENGTH: 160
      CROP_FACE:
        DO_CROP_FACE: True
        BACKEND: 'HC'
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY: 30
          USE_MEDIAN_FACE_BOX: False
      RESIZE:
        H: 72
        W: 72
DEVICE: cuda:0
NUM_OF_GPU_TRAIN: 1
LOG:
  PATH: ./logs/PhaseNet/PhysLLM_JOINT_UBFC_PURE_BUAA_MMPD_72x72_160_train_test
MODEL:
  DROP_RATE: 0.2
  NAME: PhaseNet
  PHASENET:
    PARAMS:
      FEATURE_DIM: 128
      LATENT_DIM: 32
      HIDDEN_DIM: 128
      K_STEPS: 10
      K_LR: 0.1
INFERENCE:
  BATCH_SIZE: 4
  EVALUATION_METHOD: "FFT"
  EVALUATION_WINDOW:
    USE_SMALLER_WINDOW: False
    WINDOW_SIZE: 10
  MODEL_PATH: "./logs/PhaseNet/PhysLLM_JOINT_UBFC_PURE_BUAA_MMPD_72x72_160_train_test/JOINT_SizeW72_SizeH72_ClipLength160_DataTypeRaw_DataAugNone_LabelTypeStandardized_Crop_faceTrue_BackendHC_Large_boxTrue_Large_size1.5_Dyamic_DetFalse_det_len30_Median_face_boxFalse/PreTrainedModels/PhysLLM_PhaseNet_JOINT_UBFC_PURE_BUAA_MMPD_72x72_160_Epoch29.pth"
